// is-by_pro: An open sourced social network for serious open source software enthusiasts.

// :[[ :HyperSpire-Foundation: OPEN-SOURCE-SOFTWARE: LICENSE: VERSION: 1: ]]:
// [[ "This Open Source Software is licensed
// under the terms and conditions of this contract." ]]
// [[ "We do not warrant that this software will be
// error free, that defects will be corrected, or
// that this software will meet your requirements
// for any particular application." ]]
// [[ "We disclaim all liability for any damages, 
// including and not excluding any others while not
// limited to direct, indirect, special, incidental, or 
// consequential damages, that may result from
// the use of this software, even if we have been 
// advised of the possibility of such damages." ]]
// [[ "We are not responsible for any software
// generated by third parties or by means of
// automated information systems." ]]
// [[ "All rights are reserved by HyperSpire Foundation and its 
// affiliates. Any infringement of these rights is 
// strictly forbidden and shall not be permitted under 
// any circumstance without prior contract." ]]
// [[ "We revoke permission for any Public/Private 
// Persons and fictional legal constructs for 
// censorship or surveillance without Probable Cause as 
// a violation of Civil Law." ]]
// [[ "No color-able contract, corporate statute or 
// fiction of law construct supersedes a Lawful Right.
// Title 18, U.S.C., § 242 - Deprivation Of Rights Under
// Color Of Law: https://www.justice.gov/crt/deprivation-rights-under-color-law" ]] 
// [[ "This serves as a non-expost facto reservation of All 
// Rights. This license does not expire but may be 
// updated by any later version." ]]
// [[ "This license is not a waiver of any rights and is
// not a release of liability. This license does not
// grant any license to use any trademark, service mark,
// or logo of HyperSpire Foundation or its affiliates." ]]
// [[ "Nothing else follows." ]]

use is_by_pro::{COPYRIGHT, DOMAIN, IB_CA_CERT, IB_CA_KEY, MYSQL_USER, MYSQL_DATABASE};
use actix_cors::Cors;
use actix_files::Files;
use actix_web::{cookie::Cookie, dev::Service, get, http::Method, post, web, App, HttpRequest, HttpResponse, HttpServer, Responder};
use rand::{distributions::Alphanumeric, Rng};
use serde::{Deserialize, Serialize};
use rustls::{ServerConfig, pki_types::CertificateDer};
use sqlx::{mysql::MySqlPoolOptions, MySqlPool};
use rustls_pemfile::{certs, private_key};
use std::fs::File;
use std::io::BufReader;
use uuid::Uuid;

#[derive(Clone)]
struct AppState {
  db_pool: MySqlPool,
  github_client_id: String,
  github_client_secret: String,
  github_redirect_uri: String,
}

#[derive(sqlx::FromRow)]
struct PostRow {
  ib_uid: String,
  username: String,
  postid: String,
  post: String,
  timestamp: String,
}

#[derive(sqlx::FromRow)]
struct ProRow {
  ibp: String,
  pro: String,
  location: String,
  services: String,
  website: String,
  github: String,
}

#[derive(sqlx::FromRow)]
struct ProfileLookupRow {
  ib_uid: i64,
}

#[derive(sqlx::FromRow)]
struct UsernameLookupRow {
  ib_uid: String,
}

#[derive(sqlx::FromRow)]
struct RelatedUserRow {
  username: Option<String>,
}

#[derive(Deserialize)]
struct GithubCallback {
  code: String,
  state: String,
}

#[derive(Deserialize)]
struct GithubTokenResponse {
  access_token: String,
}

#[derive(Deserialize)]
struct GithubTokenErrorResponse {
  error: String,
  error_description: Option<String>,
}

#[derive(Deserialize)]
struct GithubUser {
  login: String,
  id: u64,
}

#[derive(Deserialize)]
struct NewPostRequest {
  ib_uid: i64,
  ib_user: String,
  post: String,
}

#[derive(Deserialize)]
struct DeletePostRequest {
  ib_uid: i64,
  ib_user: String,
  pid: String,
  root_pid: Option<String>,
  post_owner_uid: Option<i64>,
}

#[derive(Deserialize)]
struct EditPostRequest {
  ib_uid: i64,
  ib_user: String,
  pid: String,
  root_pid: Option<String>,
  post_owner_uid: Option<i64>,
}

#[derive(Deserialize)]
struct EditPostUpdateRequest {
  ib_uid: i64,
  ib_user: String,
  pid: String,
  post: String,
  root_pid: Option<String>,
  post_owner_uid: Option<i64>,
}

#[derive(Deserialize)]
struct ShowPostRequest {
  ib_uid: i64,
  ib_user: String,
  pid: String,
}

#[derive(Deserialize)]
struct ReplyRequest {
  ib_uid: i64,
  ib_user: String,
  pid: String,
  post: String,
}

#[derive(Deserialize)]
struct EditProfileRequest {
  ib_uid: i64,
  ib_user: String,
}

#[derive(Deserialize)]
struct EditProfileUpdateRequest {
  ib_uid: i64,
  ib_user: String,
  ib_github: String,
  ib_ibp: String,
  ib_pro: String,
  ib_services: String,
  ib_location: String,
  ib_website: String,
}

#[derive(sqlx::FromRow)]
struct EditProfileRow {
  ib_ibp: String,
  ib_pro: String,
  ib_services: String,
  ib_location: String,
  ib_website: String,
}

#[derive(sqlx::FromRow)]
struct EditPostRow {
  post: String,
}

#[derive(Serialize)]
struct PostResponse {
  success: bool,
  message: String,
  postid: Option<String>,
}

fn load_rustls_config() -> ServerConfig {
  let cert_file = &mut BufReader::new(File::open(IB_CA_CERT).unwrap());
  let key_file  = &mut BufReader::new(File::open(IB_CA_KEY).unwrap());

  let cert_chain: Vec<CertificateDer> = certs(cert_file).map(|c| c.unwrap()).collect();
  let key = private_key(key_file).unwrap().unwrap();

  ServerConfig::builder()
    .with_no_client_auth()
    .with_single_cert(cert_chain, key)
    .unwrap()
}

fn escape_html(input: &str) -> String {
  input
    .replace('&', "&amp;")
    .replace('<', "&lt;")
    .replace('>', "&gt;")
    .replace('"', "&quot;")
    .replace('\'', "&#39;")
}

fn escape_mysql_regex_token(input: &str) -> String {
  let mut escaped = String::with_capacity(input.len());

  for ch in input.chars() {
    match ch {
      '\\' | '.' | '^' | '$' | '*' | '+' | '?' | '(' | ')' | '[' | ']' | '{' | '}' | '|' => {
        escaped.push('\\');
        escaped.push(ch);
      }
      _ => escaped.push(ch),
    }
  }

  escaped
}

async fn render_related_userlist_html(
  state: &AppState,
  current_uid: i64,
  current_pro: &str,
) -> String {
  let interests: Vec<String> = current_pro
    .split(',')
    .map(|term| term.trim().to_lowercase())
    .filter(|term| !term.is_empty())
    .collect();

  if interests.is_empty() {
    return "<p><em>:[[ :no-related-users: ]]:</em></p>".to_string();
  }

  let regex_terms: Vec<String> = interests
    .iter()
    .map(|term| escape_mysql_regex_token(term))
    .collect();
  let pattern = format!(
    "(^|[[:space:],])({})([[:space:],]|$)",
    regex_terms.join("|")
  );

  let related_rows = sqlx::query_as::<_, RelatedUserRow>(
      "SELECT u.username FROM isby.pro AS p LEFT JOIN isby.user AS u ON CONVERT(u.ib_uid USING utf8mb4) COLLATE utf8mb4_unicode_ci = CAST(p.ib_uid AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_unicode_ci WHERE p.ib_uid <> ? AND LOWER(COALESCE(p.pro, '')) REGEXP ? ORDER BY p.ib_uid DESC LIMIT 5"
    )
    .bind(current_uid)
    .bind(&pattern)
    .fetch_all(&state.db_pool)
    .await;

  let related_rows = match related_rows {
    Ok(rows) => rows,
    Err(_) => return "<p><em>:[[ :related-user-lookup-failed: ]]:</em></p>".to_string(),
  };

  let mut related_html = String::new();

  for row in related_rows {
    let username = match row.username {
      Some(username) if !username.trim().is_empty() => username,
      _ => continue,
    };

    related_html += &format!(
      r#"<p><a href="https://{domain}/v1/profile/{username}">{username}</a></p>"#,
      domain = DOMAIN,
      username = escape_html(&username)
    );
  }

  if related_html.is_empty() {
    "<p><em>:[[ :no-related-users: ]]:</em></p>".to_string()
  } else {
    related_html
  }
}

fn render_post_meta(ib_uid: &str, username: &str, timestamp: &str) -> String {
  let profile_target = if username.trim().is_empty() {
    ib_uid
  } else {
    username
  };

  format!(
    r#"<div class="post-meta"><a class="post-author" href="https://{domain}/v1/profile/{profile_target}">{username}</a><span class="post-timestamp">{timestamp}</span></div>"#,
    domain = DOMAIN,
    profile_target = escape_html(profile_target),
    username = escape_html(username),
    timestamp = escape_html(timestamp)
  )
}

fn get_session_uid(req: &HttpRequest) -> Option<i64> {
  req.cookie("ib_uid")
    .and_then(|cookie| cookie.value().parse::<i64>().ok())
}

async fn redirect_to_https(req: HttpRequest) -> HttpResponse {
  let host = req.connection_info().host().to_owned();
  let path = req.uri().path_and_query().map(|p| p.as_str()).unwrap_or("/");
  HttpResponse::MovedPermanently()
    .insert_header(("Location", format!("https://{}{}", host, path)))
    .finish()
}

async fn create_db_pool() -> Result<MySqlPool, sqlx::Error> {
  let mysql_password = std::env::var("MYSQL_PASSWORD")
    .expect("Missing MYSQL_PASSWORD in environment file or shell");

  MySqlPoolOptions::new()
    .max_connections(5)
    .connect_with(
      sqlx::mysql::MySqlConnectOptions::new()
        .host("localhost")
        .username(MYSQL_USER)
        .password(&mysql_password)
        .database(MYSQL_DATABASE),
    )
    .await
}

async fn ensure_legacy_user_from_github(
  state: &AppState,
  github_id: u64,
  github_username: &str,
) -> Result<(), sqlx::Error> {
  // CREATE TABLE isby.user (ib_uid varchar(64) PRIMARY KEY, username varchar(255));
  sqlx::query("INSERT IGNORE INTO isby.user (ib_uid, username) VALUES (?, ?)")
    .bind(github_id.to_string())
    .bind(github_username)
    .execute(&state.db_pool)
    .await?;

  Ok(())
}

async fn render_profile_html(
  state: &AppState,
  ib_uid: i64,
  ib_user: &str,
  session_uid: Option<i64>,
) -> Result<String, String> {
  let navigation_links = if session_uid.is_some() {
    format!(
      r#"<a class="post-form-display" href="javascript:void(0);">:[[ :post: ]]:</a>
        <a class="pro-home-display" href="https://{domain}/v1/profile/{ib_user}">:[[ :profile-home: ]]:</a>
        <a class="show-edit-profile" href="javascript:void(0);">:[[ :edit-profile: ]]:</a>"#,
      domain = DOMAIN,
      ib_user = escape_html(ib_user)
    )
  } else {
    String::new()
  };

  let mut html = format!(
    r#"<!DOCTYPE html>
<html lang="en-US">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/css/is-by.css">
  <script src="/js/is-by_user.js" type="text/javascript"></script>
  <title>:[[ :is-by: pro: {ib_user}: ]]:</title>
</head>

<body>
  <form id="select-user-form" action="/" method="GET">
    <input type="hidden" name="ib_uid" value="{ib_uid}">
    <input type="hidden" name="ib_user" value="{ib_user}">
  </form>
  <form id="select-post-form" action="https://{domain}/v1/showpost" method="POST">
    <input type="hidden" name="ib_uid" value="{ib_uid}">
    <input type="hidden" name="ib_user" value="{ib_user}">
  </form>
  <form id="edit-profile-form" action="https://{domain}/v1/editprofile" method="GET">
    <input type="hidden" name="ib_uid" value="{ib_uid}">
    <input type="hidden" name="ib_user" value="{ib_user}">
  </form>
  <div id="main-section">
    <div id="media-section">
      <div>
      <img src="/images/Death_Angel-555x111.png" alt=":Death_Angel-555x111.png:" width="555"
          height="111">
      </div>
      <div id="navigation-section">
        {navigation_links}
      </div>
      <div id="post-form-section">
        <form id="post-form" action="https://{domain}/v1/post" method="POST">
          <div id="post-message"></div>
          <div id="post-character-count"></div>
          <input type="hidden" name="ib_uid" value="{ib_uid}">
          <input type="hidden" name="ib_user" value="{ib_user}">
          <input class="post" type="text" name="post" autocomplete="off" maxlength="1024" required>
          <input id="post-cancel" class="post-cancel" type="button" value="Cancel">
          <input class="post-submit" type="submit" value="Post">
        </form>
      </div>"#,
    ib_user = escape_html(ib_user),
    ib_uid = ib_uid,
    navigation_links = navigation_links,
    domain = DOMAIN
  );

  let ib_post_results_maximum: usize = 200;
  let ib_post_results = sqlx::query_as::<_, PostRow>(
      "SELECT CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4) AS ib_uid, CAST(COALESCE(CONVERT(user.username USING utf8mb4), CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4)) AS CHAR CHARACTER SET utf8mb4) AS username, post.postid, post.post, post.timestamp FROM isby.post AS post LEFT JOIN isby.user AS user ON CONVERT(user.ib_uid USING utf8mb4) COLLATE utf8mb4_unicode_ci = CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_unicode_ci WHERE post.ib_uid = ? AND (post.parentid = '' OR post.parentid IS NULL)"
    )
    .bind(ib_uid)
    .fetch_all(&state.db_pool)
    .await
    .map_err(|e| format!("Post query failed: {}", e))?;

  let ib_post_results_length = ib_post_results.len();
  let mut selected_user_posts_response_content = format!(
    r#"<div class="notice"><p><em>:[[ :for-the: [[ posts: is-by: {ib_post_results_length}: is-with: showing-latest-results: truncated: is-by: {ib_post_results_maximum} ]]: ]]:</em></p></div>"#,
    ib_post_results_length = ib_post_results_length,
    ib_post_results_maximum = ib_post_results_maximum
  );

  let start_index = ib_post_results_length.saturating_sub(ib_post_results_maximum);
  for row in ib_post_results[start_index..].iter().rev() {
    let row_owner_uid = row.ib_uid.parse::<i64>().ok();
    let can_manage_post = session_uid.is_some() && session_uid == row_owner_uid;
    let manage_actions = if can_manage_post {
      format!(
        r#"<form class="delete-post-form" action="https://{domain}/v1/deletepost" method="POST">
            <input type="hidden" name="ib_uid" value="{ib_uid}">
            <input type="hidden" name="ib_user" value="{ib_user}">
            <input type="hidden" name="pid" value="{ib_post_id}">
          </form>
          <form class="edit-post-form" action="https://{domain}/v1/editpost" method="GET">
            <input type="hidden" name="ib_uid" value="{ib_uid}">
            <input type="hidden" name="ib_user" value="{ib_user}">
            <input type="hidden" name="pid" value="{ib_post_id}">
          </form>
          <a href="javascript:void(0);" class="edit-post">:[[ :edit: ]]:</a><a href="javascript:void(0);" class="delete-post">:[[ :delete: ]]:</a>"#,
        domain = DOMAIN,
        ib_uid = ib_uid,
        ib_user = escape_html(ib_user),
        ib_post_id = escape_html(&row.postid),
      )
    } else {
      String::new()
    };

    selected_user_posts_response_content += &format!(
      r#"
      <div class="post" data-postid="{ib_post_id}" data-timestamp="{ib_post_timestamp}">
        {post_meta}
        <p>{ib_post}</p>
        <div class="post-actions">
          {manage_actions}
          <form class="show-post-form" action="https://{domain}/v1/showpost" method="GET">
            <input type="hidden" name="ib_uid" value="{ib_uid}">
            <input type="hidden" name="ib_user" value="{ib_user}">
            <input type="hidden" name="pid" value="{ib_post_id}">
          </form>
          <a href="javascript:void(0);" class="show-post">:[[ :show-post: ]]:</a>
        </div>
      </div>"#,
      ib_post_id = escape_html(&row.postid),
      ib_post_timestamp = escape_html(&row.timestamp),
      post_meta = render_post_meta(&row.ib_uid, &row.username, &row.timestamp),
      manage_actions = manage_actions,
      ib_post = escape_html(&row.post),
      ib_uid = ib_uid,
      ib_user = escape_html(ib_user),
      domain = DOMAIN
    );
  }

  html += &format!(
    r#"<div id="selected-user-posts-section">{selected_user_posts_response_content}</div>"#,
    selected_user_posts_response_content = selected_user_posts_response_content
  );

  let ib_pro_result = sqlx::query_as::<_, ProRow>(
      "SELECT ibp, pro, location, services, website, github FROM isby.pro WHERE ib_uid = ?"
    )
    .bind(ib_uid)
    .fetch_one(&state.db_pool)
    .await;

  if let Ok(ib_pro) = ib_pro_result {
    let related_userlist_html = render_related_userlist_html(state, ib_uid, &ib_pro.pro).await;

    html += &format!(r#"
  </div>
  <div id="profile-section">
    <p><strong>:[[ :<a target="_blank" rel="noopener" href="{ib_github}">{ib_user}</a>: ☑️: ]]:</strong></p>
    <p class="paragraph"><em>{ib_ibp}</em></p>
    <p class="description">{ib_pro}</p>
    <p class="description">{ib_services}</p>
    <p class="description">{ib_location}</p>
    <p><a target="_blank" rel="noopener" href="{ib_website}">{ib_website}</a></p>
    <div id="userlist-section">
      <p><strong>:[[ :userlist: ]]:</strong></p>
      <div id="userlist-container">
        {related_userlist_html}
      </div>
    </div>
  </div>
</div>
</body>

</html>"#,
      ib_github = escape_html(&ib_pro.github),
      ib_user = escape_html(ib_user),
      ib_ibp = escape_html(&ib_pro.ibp),
      ib_pro = escape_html(&ib_pro.pro),
      ib_services = escape_html(&ib_pro.services),
      ib_location = escape_html(&ib_pro.location),
      ib_website = escape_html(&ib_pro.website),
      related_userlist_html = related_userlist_html
    );
  } else {
    html += &format!(r#"
    </div>
  </div>
</body>

</html>"#);
  }

  Ok(html)
}

async fn render_single_post_html(
  state: &AppState,
  ib_uid: i64,
  ib_user: &str,
  pid: &str,
  session_uid: Option<i64>,
) -> Result<String, String> {
  let post = sqlx::query_as::<_, PostRow>(
      "SELECT CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4) AS ib_uid, CAST(COALESCE(CONVERT(user.username USING utf8mb4), CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4)) AS CHAR CHARACTER SET utf8mb4) AS username, post.postid, post.post, post.timestamp FROM isby.post AS post LEFT JOIN isby.user AS user ON CONVERT(user.ib_uid USING utf8mb4) COLLATE utf8mb4_unicode_ci = CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_unicode_ci WHERE post.ib_uid = ? AND post.postid = ? LIMIT 1"
    )
    .bind(ib_uid)
    .bind(pid)
    .fetch_optional(&state.db_pool)
    .await
    .map_err(|e| format!("Post lookup failed: {}", e))?;

  let post = match post {
    Some(post) => post,
    None => return Err(format!("Post not found: {}", pid)),
  };

  let replies = sqlx::query_as::<_, PostRow>(
      "SELECT CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4) AS ib_uid, CAST(COALESCE(CONVERT(user.username USING utf8mb4), CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4)) AS CHAR CHARACTER SET utf8mb4) AS username, post.postid, post.post, post.timestamp FROM isby.post AS post LEFT JOIN isby.user AS user ON CONVERT(user.ib_uid USING utf8mb4) COLLATE utf8mb4_unicode_ci = CAST(post.ib_uid AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_unicode_ci WHERE post.parentid = ? ORDER BY post.timestamp ASC"
    )
    .bind(pid)
    .fetch_all(&state.db_pool)
    .await
    .map_err(|e| format!("Reply lookup failed: {}", e))?;

  let mut replies_html = String::new();

  if !replies.is_empty() {
    for reply in replies {
      let reply_owner_uid = escape_html(&reply.ib_uid);
      let can_manage_reply = session_uid.is_some() && session_uid == reply.ib_uid.parse::<i64>().ok();
      let reply_manage_actions = if can_manage_reply {
        format!(
          r#"<div class="post-actions">
            <form class="delete-post-form" action="https://{domain}/v1/deletepost" method="POST">
              <input type="hidden" name="ib_uid" value="{page_ib_uid}">
              <input type="hidden" name="ib_user" value="{page_ib_user}">
              <input type="hidden" name="pid" value="{reply_post_id}">
              <input type="hidden" name="root_pid" value="{root_pid}">
              <input type="hidden" name="post_owner_uid" value="{reply_owner_uid}">
            </form>
            <form class="edit-post-form" action="https://{domain}/v1/editpost" method="GET">
              <input type="hidden" name="ib_uid" value="{page_ib_uid}">
              <input type="hidden" name="ib_user" value="{page_ib_user}">
              <input type="hidden" name="pid" value="{reply_post_id}">
              <input type="hidden" name="root_pid" value="{root_pid}">
              <input type="hidden" name="post_owner_uid" value="{reply_owner_uid}">
            </form>
            <a href="javascript:void(0);" class="edit-post">:[[ :edit: ]]:</a><a href="javascript:void(0);" class="delete-post">:[[ :delete: ]]:</a>
          </div>"#,
          domain = DOMAIN,
          page_ib_uid = ib_uid,
          page_ib_user = escape_html(ib_user),
          root_pid = escape_html(pid),
          reply_post_id = escape_html(&reply.postid),
          reply_owner_uid = reply_owner_uid,
        )
      } else {
        String::new()
      };

      replies_html += &format!(
        r#"
        <div class="post reply-post" data-postid="{reply_post_id}" data-timestamp="{reply_post_timestamp}">
          {reply_post_meta}
          <p>{reply_post}</p>
          {reply_manage_actions}
        </div>"#,
        reply_post_id = escape_html(&reply.postid),
        reply_post_timestamp = escape_html(&reply.timestamp),
        reply_post_meta = render_post_meta(&reply.ib_uid, &reply.username, &reply.timestamp),
        reply_post = escape_html(&reply.post),
        reply_manage_actions = reply_manage_actions
      );
    }
  }

  let mut html = format!(
    r#"<!DOCTYPE html>
<html lang="en-US">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/css/is-by.css">
  <script src="/js/is-by_user.js" type="text/javascript"></script>
  <title>:[[ :is-by: pro: {ib_user}: ]]:</title>
</head>

<body>
  <form id="select-user-form" action="/" method="GET">
    <input type="hidden" name="ib_uid" value="{ib_uid}">
    <input type="hidden" name="ib_user" value="{ib_user}">
  </form>
  <div id="main-section">
    <div id="media-section">
      <div>
      <img src="/images/Death_Angel-555x111.png" alt=":Death_Angel-555x111.png:" width="555"
          height="111">
      </div>
      <div id="navigation-section">
        <a class="pro-home-display" href="https://{domain}/v1/profile/{ib_user}">:[[ :profile-home: ]]:</a>
      </div>
      <div id="selected-user-posts-section" class="post-section">
        <div class="post" data-postid="{ib_post_id}" data-timestamp="{ib_post_timestamp}">
          {post_meta}
          <p>{ib_post}</p>
          <div class="post-actions">
            <p><a href="javascript:void(0);" class="copy-link">:[[ :copy-link: ]]:</a></p>
          </div>
        </div>
        {replies_html}
        <div id="post-form-section" style="display:block;">
          <form id="reply-form" action="https://{domain}/v1/reply" method="POST">
            <input type="hidden" name="ib_uid" value="{ib_uid}">
            <input type="hidden" name="ib_user" value="{ib_user}">
            <input type="hidden" name="pid" value="{ib_post_id}">
            <input type="text" class="post" name="post" maxlength="1024" required>
            <br>
            <input class="post-submit" type="submit" value="Reply">
          </form>
        </div>
      </div>"#,
    domain = DOMAIN,
    ib_uid = ib_uid,
    ib_user = escape_html(ib_user),
    ib_post_id = escape_html(&post.postid),
    ib_post_timestamp = escape_html(&post.timestamp),
    post_meta = render_post_meta(&post.ib_uid, &post.username, &post.timestamp),
    ib_post = escape_html(&post.post),
    replies_html = replies_html
  );

  let ib_pro_result = sqlx::query_as::<_, ProRow>(
      "SELECT ibp, pro, location, services, website, github FROM isby.pro WHERE ib_uid = ?"
    )
    .bind(ib_uid)
    .fetch_one(&state.db_pool)
    .await;

  if let Ok(ib_pro) = ib_pro_result {
    let related_userlist_html = render_related_userlist_html(state, ib_uid, &ib_pro.pro).await;

    html += &format!(r#"
  </div>
  <div id="profile-section">
    <p><strong>:[[ :<a target="_blank" rel="noopener" href="{ib_github}">{ib_user}</a>: ☑️: ]]:</strong></p>
    <p class="paragraph"><em>{ib_ibp}</em></p>
    <p class="description">{ib_pro}</p>
    <p class="description">{ib_services}</p>
    <p class="description">{ib_location}</p>
    <p><a target="_blank" rel="noopener" href="{ib_website}">{ib_website}</a></p>
    <div id="userlist-section">
      <p><strong>:[[ :userlist: ]]:</strong></p>
      <div id="userlist-container">
        {related_userlist_html}
      </div>
    </div>
  </div>
</div>
</body>

</html>"#,
      ib_github = escape_html(&ib_pro.github),
      ib_user = escape_html(ib_user),
      ib_ibp = escape_html(&ib_pro.ibp),
      ib_pro = escape_html(&ib_pro.pro),
      ib_services = escape_html(&ib_pro.services),
      ib_location = escape_html(&ib_pro.location),
      ib_website = escape_html(&ib_pro.website),
      related_userlist_html = related_userlist_html
    );
  } else {
    html += &format!(r#"
    </div>
  </div>
</body>

</html>"#);
  }

  Ok(html)
}

#[post("/v1/post")]
async fn create_post(
  state: web::Data<AppState>,
  payload: web::Json<NewPostRequest>,
) -> impl Responder {
  const MAX_POST_LEN: usize = 1024;

  if payload.post.trim().is_empty() {
    return HttpResponse::BadRequest().json(PostResponse {
      success: false,
      message: "Post cannot be empty".to_string(),
      postid: None,
    });
  }

  if payload.post.chars().count() > MAX_POST_LEN {
    return HttpResponse::BadRequest().json(PostResponse {
      success: false,
      message: format!("Post cannot exceed {} characters", MAX_POST_LEN),
      postid: None,
    });
  }

  let postid = Uuid::new_v4().to_string();

  // CREATE TABLE isby.post (ib_uid varchar(64), postid varchar(64), parentid varchar(64), post varchar(1024), timestamp varchar(32));
  // ALTER TABLE isby.post MODIFY COLUMN parentid VARCHAR(64) NOT NULL DEFAULT '';
  let result = sqlx::query(
    "INSERT INTO isby.post (ib_uid, postid, post, `timestamp`) VALUES (?, ?, ?, NOW())",
  )
  .bind(payload.ib_uid)
  .bind(&postid)
  .bind(&payload.post)
  .execute(&state.db_pool)
  .await;

  match result {
    Ok(_) => HttpResponse::Ok()
      .insert_header(("ib_user", payload.ib_user.clone()))
      .json(PostResponse {
        success: true,
        message: "Post created".to_string(),
        postid: Some(postid),
      }),
    Err(err) => HttpResponse::InternalServerError().json(PostResponse {
      success: false,
      message: format!("Failed to create post: {}", err),
      postid: None,
    }),
  }
}

#[post("/v1/reply")]
async fn create_reply(
  state: web::Data<AppState>,
  payload: web::Form<ReplyRequest>,
) -> impl Responder {
  const MAX_POST_LEN: usize = 1024;

  if payload.post.trim().is_empty() {
    return HttpResponse::BadRequest().body("Reply cannot be empty");
  }

  if payload.post.chars().count() > MAX_POST_LEN {
    return HttpResponse::BadRequest()
      .body(format!("Reply cannot exceed {} characters", MAX_POST_LEN));
  }

  let replyid = Uuid::new_v4().to_string();

  let result = sqlx::query(
    "INSERT INTO isby.post (ib_uid, postid, parentid, post, `timestamp`) VALUES (?, ?, ?, ?, NOW())",
  )
  .bind(payload.ib_uid)
  .bind(&replyid)
  .bind(&payload.pid)
  .bind(&payload.post)
  .execute(&state.db_pool)
  .await;

  match result {
    Ok(_) => HttpResponse::SeeOther()
      .insert_header((
        "Location",
        format!(
          "/v1/showpost?ib_uid={}&ib_user={}&pid={}",
          payload.ib_uid, payload.ib_user, payload.pid
        ),
      ))
      .finish(),
    Err(err) => HttpResponse::InternalServerError()
      .body(format!("Failed to create reply: {}", err)),
  }
}

#[post("/v1/showpost")]
async fn show_post(
  req: HttpRequest,
  state: web::Data<AppState>,
  payload: web::Form<ShowPostRequest>,
) -> impl Responder {
  render_show_post_response(
    &state,
    payload.ib_uid,
    &payload.ib_user,
    &payload.pid,
    get_session_uid(&req),
  )
  .await
}

#[get("/v1/showpost")]
async fn show_post_get(
  req: HttpRequest,
  state: web::Data<AppState>,
  query: web::Query<ShowPostRequest>,
) -> impl Responder {
  render_show_post_response(
    &state,
    query.ib_uid,
    &query.ib_user,
    &query.pid,
    get_session_uid(&req),
  )
  .await
}

async fn render_show_post_response(
  state: &AppState,
  ib_uid: i64,
  ib_user: &str,
  pid: &str,
  session_uid: Option<i64>,
) -> HttpResponse {
  match render_single_post_html(state, ib_uid, ib_user, pid, session_uid).await {
    Ok(html) => HttpResponse::Ok()
      .content_type("text/html; charset=utf-8")
      .body(html),
    Err(err) if err.starts_with("Post not found:") => HttpResponse::NotFound()
      .content_type("text/html; charset=utf-8")
      .body(format!(
        "<!DOCTYPE html><html lang=\"en-US\"><head><meta charset=\"UTF-8\"><title>Post Not Found</title></head><body><p>{}</p></body></html>",
        escape_html(&err)
      )),
    Err(err) => HttpResponse::InternalServerError().body(err),
  }
}

#[get("/v1/editprofile")]
async fn edit_profile(
  state: web::Data<AppState>,
  query: web::Query<EditProfileRequest>,
) -> impl Responder {
  let row = match sqlx::query_as::<_, EditProfileRow>(
    "SELECT github AS ib_github, ibp AS ib_ibp, pro AS ib_pro, services AS ib_services, location AS ib_location, website AS ib_website FROM isby.pro WHERE ib_uid = ? LIMIT 1",
  )
  .bind(query.ib_uid)
  .fetch_optional(&state.db_pool)
  .await
  {
    Ok(Some(row)) => row,
    Ok(None) => EditProfileRow {
      ib_ibp: String::new(),
      ib_pro: String::new(),
      ib_services: String::new(),
      ib_location: String::new(),
      ib_website: String::new(),
    },
    Err(err) => {
      return HttpResponse::InternalServerError().body(format!("Edit profile lookup failed: {}", err));
    }
  };

  let html = format!(
    r#"<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="/css/is-by.css" />
  <script src="/js/is-by_user.js" type="text/javascript"></script>
  <title>:[[ :edit-profile: {ib_user}: ]]:</title>
</head>
<body>
  <div id="main-section">
    <div id="media-section">
      <div>
        <img src="/images/Death_Angel-555x111.png" alt=":Death_Angel-555x111.png:" width="555" height="111">
      </div>
      <div id="navigation-section">
        <a class="pro-home-display" href="https://{domain}/v1/profile/{ib_user}">:[[ :profile-home: ]]:</a>
      </div>
      <div id="post-form-section" style="display:block;">
        <form id="edit-profile-form" action="https://{domain}/v1/editprofile" method="POST">
          <input type="hidden" name="ib_uid" value="{ib_uid}">
          <input type="hidden" name="ib_user" value="{ib_user}">
          GitHub: https://github.com/<input class="post" type="text" name="ib_github" placeholder="{ib_user}" autocomplete="off"><br>
          About Me: <input class="post" type="text" name="ib_ibp" value="{ib_ibp}" placeholder="{ib_ibp}" autocomplete="off"><br>
          Interests: <input class="post" type="text" name="ib_pro" value="{ib_pro}" placeholder="{ib_pro}" autocomplete="off"><br>
          Services: <input class="post" type="text" name="ib_services" value="{ib_services}" placeholder="{ib_services}" autocomplete="off"><br>
          Location: <input class="post" type="text" name="ib_location" value="{ib_location}" placeholder="{ib_location}" autocomplete="off"><br>
          Website: <input class="post" type="text" name="ib_website" value="{ib_website}" placeholder="{ib_website}" autocomplete="off"><br>
          <input class="post-submit" type="submit" value="Save">
        </form>
      </div>
    </div>
  </div>
</body>
</html>"#,
    domain = DOMAIN,
    ib_uid = query.ib_uid,
    ib_user = escape_html(&query.ib_user),
    ib_ibp = escape_html(&row.ib_ibp),
    ib_pro = escape_html(&row.ib_pro),
    ib_services = escape_html(&row.ib_services),
    ib_location = escape_html(&row.ib_location),
    ib_website = escape_html(&row.ib_website)
  );

  HttpResponse::Ok()
    .content_type("text/html; charset=utf-8")
    .body(html)
}

#[post("/v1/editprofile")]
async fn update_profile(
  state: web::Data<AppState>,
  payload: web::Form<EditProfileUpdateRequest>,
) -> impl Responder {
  let update_result = sqlx::query(
    "UPDATE isby.pro SET github = ?, ibp = ?, pro = ?, services = ?, location = ?, website = ? WHERE ib_uid = ?",
  )
  .bind(&payload.ib_github)
  .bind(&payload.ib_ibp)
  .bind(&payload.ib_pro)
  .bind(&payload.ib_services)
  .bind(&payload.ib_location)
  .bind(&payload.ib_website)
  .bind(payload.ib_uid)
  .execute(&state.db_pool)
  .await;

  match update_result {
    Ok(update_done) if update_done.rows_affected() > 0 => HttpResponse::SeeOther()
      .insert_header(("Location", format!("/v1/profile/{}", payload.ib_user)))
      .finish(),
    Ok(_) => {
      let insert_result = sqlx::query(
        "INSERT INTO isby.pro (ib_uid, github, ibp, pro, services, location, website) VALUES (?, ?, ?, ?, ?, ?, ?)",
      )
      .bind(payload.ib_uid)
      .bind(&payload.ib_github)
      .bind(&payload.ib_ibp)
      .bind(&payload.ib_pro)
      .bind(&payload.ib_services)
      .bind(&payload.ib_location)
      .bind(&payload.ib_website)
      .execute(&state.db_pool)
      .await;

      match insert_result {
        Ok(_) => HttpResponse::SeeOther()
          .insert_header(("Location", format!("/v1/profile/{}", payload.ib_user)))
          .finish(),
        Err(err) => HttpResponse::InternalServerError()
          .body(format!("Failed to create profile: {}", err)),
      }
    }
    Err(err) => HttpResponse::InternalServerError()
      .body(format!("Failed to update profile: {}", err)),
  }
}

#[post("/v1/deletepost")]
async fn delete_post(
  req: HttpRequest,
  state: web::Data<AppState>,
  payload: web::Form<DeletePostRequest>,
) -> impl Responder {
  let session_uid = match get_session_uid(&req) {
    Some(uid) => uid,
    None => return HttpResponse::Unauthorized().body("Login required"),
  };

  let owner_uid = payload.post_owner_uid.unwrap_or(payload.ib_uid);
  if session_uid != owner_uid {
    return HttpResponse::Forbidden().body("You can only delete your own posts");
  }

  let result = sqlx::query(
    "DELETE FROM isby.post WHERE ib_uid = ? AND postid = ?",
  )
  .bind(owner_uid)
  .bind(&payload.pid)
  .execute(&state.db_pool)
  .await;

  match result {
    Ok(_) => {
      let location = if let Some(root_pid) = payload.root_pid.as_deref() {
        format!(
          "/v1/showpost?ib_uid={}&ib_user={}&pid={}",
          payload.ib_uid, payload.ib_user, root_pid
        )
      } else {
        format!("/v1/profile/{}", payload.ib_user)
      };

      HttpResponse::SeeOther()
        .insert_header(("Location", location))
        .finish()
    }
    Err(err) => HttpResponse::InternalServerError()
      .body(format!("Failed to delete post: {}", err)),
  }
}

#[get("/v1/editpost")]
async fn edit_post(
  req: HttpRequest,
  state: web::Data<AppState>,
  query: web::Query<EditPostRequest>,
) -> impl Responder {
  let session_uid = match get_session_uid(&req) {
    Some(uid) => uid,
    None => return HttpResponse::Unauthorized().body("Login required"),
  };

  let owner_uid = query.post_owner_uid.unwrap_or(query.ib_uid);
  if session_uid != owner_uid {
    return HttpResponse::Forbidden().body("You can only edit your own posts");
  }

  let selected = sqlx::query_as::<_, EditPostRow>(
    "SELECT post FROM isby.post WHERE ib_uid = ? AND postid = ? LIMIT 1",
  )
  .bind(owner_uid)
  .bind(&query.pid)
  .fetch_optional(&state.db_pool)
  .await;

  let row = match selected {
    Ok(Some(row)) => row,
    Ok(None) => {
      return HttpResponse::NotFound()
        .content_type("text/html; charset=utf-8")
        .body(format!(
          "<!DOCTYPE html><html lang=\"en-US\"><head><meta charset=\"UTF-8\"><title>Post Not Found</title></head><body><p>Post not found: {}</p></body></html>",
          escape_html(&query.pid)
        ));
    }
    Err(err) => {
      return HttpResponse::InternalServerError().body(format!("Edit post lookup failed: {}", err));
    }
  };

  let root_pid_field = query.root_pid.as_ref().map(|root_pid| {
    format!(
      r#"<input type="hidden" name="root_pid" value="{}">"#,
      escape_html(root_pid)
    )
  }).unwrap_or_default();

  let post_owner_uid_field = query.post_owner_uid.map(|post_owner_uid| {
    format!(
      r#"<input type="hidden" name="post_owner_uid" value="{}">"#,
      post_owner_uid
    )
  }).unwrap_or_default();

  let html = format!(
    r#"<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="/css/is-by.css" />
  <title>:[[ :edit-post: ]]:</title>
</head>
<body>
  <div id="main-section">
    <div id="media-section">
      <div id="navigation-section">
        <a class="pro-home-display" href="https://{domain}/v1/profile/{ib_user}">:[[ :profile-home: ]]:</a>
      </div>
      <div id="post-form-section" style="display:block;">
        <form id="editpost" action="https://{domain}/v1/editpost" method="POST">
          <div id="edit-post-message"></div>
          <input type="hidden" name="ib_uid" value="{ib_uid}">
          <input type="hidden" name="ib_user" value="{ib_user}">
          <input type="hidden" name="pid" value="{pid}">
          {root_pid_field}
          {post_owner_uid_field}
          <input type="text" class="post" name="post" maxlength="1024" value="{post}" required>
          <br>
          <input class="post-submit" type="submit" value="Save">
        </form>
      </div>
    </div>
  </div>
</body>
</html>"#,
    domain = DOMAIN,
    ib_uid = query.ib_uid,
    ib_user = escape_html(&query.ib_user),
    pid = escape_html(&query.pid),
    root_pid_field = root_pid_field,
    post_owner_uid_field = post_owner_uid_field,
    post = escape_html(&row.post)
  );

  HttpResponse::Ok()
    .content_type("text/html; charset=utf-8")
    .body(html)
}

#[post("/v1/editpost")]
async fn update_post(
  req: HttpRequest,
  state: web::Data<AppState>,
  payload: web::Form<EditPostUpdateRequest>,
) -> impl Responder {
  const MAX_POST_LEN: usize = 1024;

  let session_uid = match get_session_uid(&req) {
    Some(uid) => uid,
    None => return HttpResponse::Unauthorized().body("Login required"),
  };

  let owner_uid = payload.post_owner_uid.unwrap_or(payload.ib_uid);
  if session_uid != owner_uid {
    return HttpResponse::Forbidden().body("You can only edit your own posts");
  }

  if payload.post.trim().is_empty() {
    return HttpResponse::BadRequest().body("Post cannot be empty");
  }

  if payload.post.chars().count() > MAX_POST_LEN {
    return HttpResponse::BadRequest()
      .body(format!("Post cannot exceed {} characters", MAX_POST_LEN));
  }

  let result = sqlx::query(
    "UPDATE isby.post SET post = ? WHERE ib_uid = ? AND postid = ?",
  )
  .bind(&payload.post)
  .bind(owner_uid)
  .bind(&payload.pid)
  .execute(&state.db_pool)
  .await;

  match result {
    Ok(_) => {
      let location = if let Some(root_pid) = payload.root_pid.as_deref() {
        format!(
          "/v1/showpost?ib_uid={}&ib_user={}&pid={}",
          payload.ib_uid, payload.ib_user, root_pid
        )
      } else {
        format!("/v1/profile/{}", payload.ib_user)
      };

      HttpResponse::SeeOther()
        .insert_header(("Location", location))
        .finish()
    }
    Err(err) => HttpResponse::InternalServerError()
      .body(format!("Failed to update post: {}", err)),
  }
}

#[get("/v1/profile/{ib_user}")]
async fn view_profile(
  req: HttpRequest,
  path: web::Path<String>,
  state: web::Data<AppState>,
) -> impl Responder {
  let ib_user = path.into_inner();

  if let Some(stripped) = ib_user.strip_prefix('@') {
    return HttpResponse::PermanentRedirect()
      .insert_header(("Location", format!("/v1/profile/{}", stripped)))
      .finish();
  }

  let normalized = ib_user.clone();

  // 1) Accept numeric uid directly in path.
  let mut resolved_uid = normalized.parse::<i64>().ok();

  // 2) Resolve from profile github handle.
  if resolved_uid.is_none() {
    let lookup = sqlx::query_as::<_, ProfileLookupRow>(
      "SELECT ib_uid FROM isby.pro WHERE LOWER(github) = LOWER(?) LIMIT 1",
    )
    .bind(&normalized)
    .fetch_optional(&state.db_pool)
    .await;

    match lookup {
      Ok(Some(row)) => resolved_uid = Some(row.ib_uid),
      Ok(None) => {}
      Err(err) => {
        return HttpResponse::InternalServerError().body(format!("Profile lookup failed: {}", err));
      }
    }
  }

  // CREATE TABLE isby.user (ib_uid varchar(64) PRIMARY KEY, username varchar(255));
  // 3) Fallback by username in legacy user table.
  if resolved_uid.is_none() {
    let user_lookup = sqlx::query_as::<_, UsernameLookupRow>(
      "SELECT ib_uid FROM isby.user WHERE LOWER(username) = LOWER(?) LIMIT 1",
    )
    .bind(&normalized)
    .fetch_optional(&state.db_pool)
    .await;

    match user_lookup {
      Ok(Some(row)) => {
        if let Ok(parsed) = row.ib_uid.parse::<i64>() {
          resolved_uid = Some(parsed);
        }
      }
      Ok(None) => {}
      Err(err) => {
        return HttpResponse::InternalServerError().body(format!("Username lookup failed: {}", err));
      }
    }
  }

  let ib_uid = match resolved_uid {
    Some(uid) => uid,
    None => {
      return HttpResponse::NotFound()
        .content_type("text/html; charset=utf-8")
        .body(format!(
          "<!DOCTYPE html><html lang=\"en-US\"><head><meta charset=\"UTF-8\"><title>Profile Not Found</title></head><body><p>Profile not found: {}</p></body></html>",
          escape_html(&ib_user)
        ));
    }
  };

  match render_profile_html(&state, ib_uid, &ib_user, get_session_uid(&req)).await {
    Ok(html) => HttpResponse::Ok()
      .content_type("text/html; charset=utf-8")
      .body(html),
    Err(err) => HttpResponse::InternalServerError().body(err),
  }
}

#[get("/auth/github")]
async fn github_auth_start(state: web::Data<AppState>) -> impl Responder {
  let oauth_state: String = rand::thread_rng()
    .sample_iter(&Alphanumeric)
    .take(32)
    .map(char::from)
    .collect();

  let url = format!(
    "https://github.com/login/oauth/authorize?client_id={}&redirect_uri={}&scope=read:user%20user:email&state={}",
    state.github_client_id,
    state.github_redirect_uri,
    oauth_state
  );

  HttpResponse::Found()
    .insert_header(("Location", url))
    .cookie(
      Cookie::build("gh_oauth_state", oauth_state)
        .path("/")
        .http_only(true)
        .secure(true)
        .finish(),
    )
    .finish()
}

#[get("/auth/github/callback")]
async fn github_auth_callback(
  req: HttpRequest,
  query: web::Query<GithubCallback>,
  state: web::Data<AppState>,
) -> impl Responder {
  let cookie_state = match req.cookie("gh_oauth_state") {
    Some(c) => c.value().to_string(),
    None => return HttpResponse::BadRequest().body("Missing oauth state cookie"),
  };

  if cookie_state != query.state {
    return HttpResponse::BadRequest().body("Invalid oauth state");
  }

  let client = reqwest::Client::new();
  let token_res = match client
    .post("https://github.com/login/oauth/access_token")
    .header("Accept", "application/json")
    .form(&[
      ("client_id", state.github_client_id.as_str()),
      ("client_secret", state.github_client_secret.as_str()),
      ("code", query.code.as_str()),
      ("redirect_uri", state.github_redirect_uri.as_str()),
    ])
    .send()
    .await
  {
    Ok(r) => r,
    Err(_) => return HttpResponse::InternalServerError().body("GitHub token request failed"),
  };

  let token_status = token_res.status();
  let token_body = match token_res.text().await {
    Ok(body) => body,
    Err(_) => return HttpResponse::InternalServerError().body("Failed to read token response"),
  };

  let token_data = if token_status.is_success() {
    match serde_json::from_str::<GithubTokenResponse>(&token_body) {
      Ok(d) => d,
      Err(_) => {
        return HttpResponse::InternalServerError().body(format!(
          "Invalid token response body: {}",
          token_body
        ))
      }
    }
  } else {
    if let Ok(err_data) = serde_json::from_str::<GithubTokenErrorResponse>(&token_body) {
      return HttpResponse::BadRequest().body(format!(
        "GitHub token error: {} ({})",
        err_data.error,
        err_data.error_description.unwrap_or_else(|| "no description".to_string())
      ));
    }

    return HttpResponse::BadRequest().body(format!(
      "GitHub token exchange failed (status {}): {}",
      token_status,
      token_body
    ));
  };

  let user_res = match client
    .get("https://api.github.com/user")
    .header("User-Agent", "is-by_pro")
    .bearer_auth(token_data.access_token)
    .send()
    .await
  {
    Ok(r) => r,
    Err(_) => return HttpResponse::InternalServerError().body("GitHub user request failed"),
  };

  let user = match user_res.json::<GithubUser>().await {
    Ok(u) => u,
    Err(_) => return HttpResponse::InternalServerError().body("Invalid user response"),
  };

  if let Err(err) = ensure_legacy_user_from_github(&state, user.id, &user.login).await {
    return HttpResponse::InternalServerError()
      .body(format!("Failed to persist GitHub user: {}", err));
  }

  match render_profile_html(&state, user.id as i64, &user.login, Some(user.id as i64)).await {
    Ok(html) => HttpResponse::Ok()
      .content_type("text/html; charset=utf-8")
      .cookie(
        Cookie::build("ib_uid", user.id.to_string())
          .path("/")
          .http_only(true)
          .secure(true)
          .finish(),
      )
      .cookie(
        Cookie::build("ib_user", user.login.clone())
          .path("/")
          .http_only(true)
          .secure(true)
          .finish(),
      )
      .body(html),
    Err(err) => HttpResponse::InternalServerError().body(err),
  }
}

#[get("/")]
async fn hello() -> impl Responder {
  let html = format!(r#"<!DOCTYPE html>
<html lang="en-US">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/css/is-by.css">
  <script src="/js/is-by_user.js" type="text/javascript"></script>
  <title>:[[ :is-by: pro: anti-social: social-media: ]]:</title>
</head>

<body>
  <div id="main-section">
    <div id="media-section">
      <img src="/images/Death_Angel-555x222.png" alt=":Death_Angel-555x222.png:" width="555"
        height="222">
      <div class="for-the">
        <p><em>:[[ :for-the: [[ QWOD-MJ12: ATSOSSDEV-A: HyperSpire-Foundation: is-with: GitHub-driven: social-media: ]]: ]]:</em></p>
      </div>
      <div class="is-by">
        <h1 class="warno">:[[ :is-by: pro: for-the: [[ anti-social: social-media: for-the: [[ PEOPLE: is-by: WE: people: ]]: ]]: ]]:</h1>
      </div>
      <div class="is-with">
        :[[ :is-with: <a href="https://github.com/hyperspire">HyperSpire-Foundation</a>: ]]:
      </div>

      <div id="footer-section">
        <p class="copyright">:[[ :for-the: [[ is-by: pro: is-by: @: {copyright}: is-with: <a target="_blank"
          rel="noopener" href="http://hyperspire.com/">HyperSpire-Foundation</a>:
          for-the: [[ Death-Angel: is-by: @: is-with: <a target="_blank"
            rel="noopener" href="https://www.youtube.com/@WhiteBatAudio">Karl-Casey</a>: ]]: ]]: ]]:</p>
      </div>
    </div>
    <div id="actions-section">
      <div class="login-section">
        <p><a href="/auth/github">Login with GitHub</a></p>
    </div>

  </div>
</body>

</html>"#, copyright = COPYRIGHT);
  HttpResponse::Ok().body(html)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
  rustls::crypto::aws_lc_rs::default_provider()
    .install_default()
    .expect("Failed to install rustls crypto provider");

  let _ = dotenvy::from_filename(".env");
  let _ = dotenvy::from_filename(".env/GITHUB_CLIENT_SECRET.env");
  let _ = dotenvy::from_filename(".env/MYSQL_PASSWORD.env");

  let db_pool = create_db_pool()
    .await
    .expect("Failed to connect to MySQL");

  let app_state = AppState {
    db_pool,
    github_client_id: std::env::var("GITHUB_CLIENT_ID")
      .expect("Missing GITHUB_CLIENT_ID in environment file or shell"),
    github_client_secret: std::env::var("GITHUB_CLIENT_SECRET")
      .expect("Missing GITHUB_CLIENT_SECRET in environment file or shell"),
    github_redirect_uri: std::env::var("GITHUB_REDIRECT_URI")
      .expect("Missing GITHUB_REDIRECT_URI in environment file or shell"),
  };

  let http_server = HttpServer::new(|| {
    App::new().default_service(web::to(redirect_to_https))
  })
  .bind(("0.0.0.0", 80))?
  .run();

  let https_server = HttpServer::new(move || {
    let allowed_origin = format!("https://{}", DOMAIN);
    let cors = Cors::default()
      .allowed_origin(&allowed_origin)
      .allowed_methods(vec!["GET", "POST"])
      .allow_any_header();

    App::new()
      .wrap(cors)
      .wrap_fn(move |req, srv| {
        let method = req.method().clone();
        let host = req
          .connection_info()
          .host()
          .split(':')
          .next()
          .unwrap_or_default()
          .to_owned();
        let host_ok = host.eq_ignore_ascii_case(DOMAIN);

        let origin_ok = req
          .headers()
          .get("origin")
          .and_then(|v| v.to_str().ok())
          .map(|origin| origin.eq_ignore_ascii_case(&allowed_origin))
          .unwrap_or(true);

        let method_ok = method == Method::GET || method == Method::POST;

        type MiddlewareFuture = std::pin::Pin<
          Box<
            dyn std::future::Future<
              Output = Result<
                actix_web::dev::ServiceResponse<
                  actix_web::body::EitherBody<actix_web::body::BoxBody>
                >,
                actix_web::Error,
              >,
            >,
          >,
        >;

        if !host_ok || !origin_ok {
          let response = req.into_response(HttpResponse::Forbidden().body("Forbidden"));
          let fut: MiddlewareFuture = Box::pin(async move {
            Ok(response.map_into_right_body::<actix_web::body::BoxBody>())
          });
          return fut;
        }

        if !method_ok {
          let response = req.into_response(HttpResponse::MethodNotAllowed().body("Method Not Allowed"));
          let fut: MiddlewareFuture = Box::pin(async move {
            Ok(response.map_into_right_body::<actix_web::body::BoxBody>())
          });
          return fut;
        }

        let fut = srv.call(req);
        let fut: MiddlewareFuture = Box::pin(async move {
          let res = fut.await?;
          let res = res.map_into_boxed_body();
          Ok(res.map_into_left_body::<actix_web::body::BoxBody>())
        });
        fut
      })
      .app_data(web::Data::new(app_state.clone()))
      .service(hello)
      .service(create_post)
      .service(create_reply)
      .service(show_post)
      .service(show_post_get)
      .service(edit_profile)
      .service(update_profile)
      .service(delete_post)
      .service(edit_post)
      .service(update_post)
      .service(view_profile)
      .service(github_auth_start)
      .service(github_auth_callback)
      .service(Files::new("/", "./webroot"))
  })
  .bind_rustls_0_23(("0.0.0.0", 443), load_rustls_config())?
  .run();

  tokio::try_join!(http_server, https_server)?;
  Ok(())
}