// is-by_pro: An open sourced social network for serious open source software enthusiasts.

// :[[ :HyperSpire-Foundation: OPEN-SOURCE-SOFTWARE: LICENSE: VERSION: 1: ]]:
// [[ "This Open Source Software is licensed
// under the terms and conditions of this contract." ]]
// [[ "We do not warrant that this software will be
// error free, that defects will be corrected, or
// that this software will meet your requirements
// for any particular application." ]]
// [[ "We disclaim all liability for any damages, 
// including and not excluding any others while not
// limited to direct, indirect, special, incidental, or 
// consequential damages, that may result from
// the use of this software, even if we have been 
// advised of the possibility of such damages." ]]
// [[ "We are not responsible for any software
// generated by third parties or by means of
// automated information systems." ]]
// [[ "All rights are reserved by HyperSpire Foundation and its 
// affiliates. Any infringement of these rights is 
// strictly forbidden and shall not be permitted under 
// any circumstance without prior contract." ]]
// [[ "We revoke permission for any Public/Private 
// Persons and fictional legal constructs for 
// censorship or surveillance without Probable Cause as 
// a violation of Civil Law." ]]
// [[ "No color-able contract, corporate statute or 
// fiction of law construct supersedes a Lawful Right.
// Title 18, U.S.C., § 242 - Deprivation Of Rights Under
// Color Of Law: https://www.justice.gov/crt/deprivation-rights-under-color-law" ]] 
// [[ "This serves as a non-expost facto reservation of All 
// Rights. This license does not expire but may be 
// updated by any later version." ]]
// [[ "This license is not a waiver of any rights and is
// not a release of liability. This license does not
// grant any license to use any trademark, service mark,
// or logo of HyperSpire Foundation or its affiliates." ]]
// [[ "Nothing else follows." ]]

use is_by_pro::{
  DOMAIN,
  HTTP_PORT,
  HTTPS_PORT,
  GITHUB_CLIENT_SECRET_ENV,
  IB_CA_CERT,
  IB_CA_KEY,
  IB_ENV,
  MYSQL_DATABASE,
  MYSQL_ENV,
  PAYPAL_ENV,
  MYSQL_USER,
  AD_ADMIN_UID,
  AD_ADMIN_USER,
  AES256_KEY_ENV,
};

use actix_cors::Cors;
use actix_files::Files;
use actix_web::{dev::Service, http::Method, web, App, HttpResponse, HttpServer};

use rustls::{ServerConfig, pki_types::CertificateDer};
use rustls_pemfile::{certs, private_key};
use std::fs::File;
use std::io::BufReader;

pub mod models;
pub use models::*;
pub mod db;
pub use db::*;
pub mod auth;
pub use auth::*;
pub mod paypal;
pub use paypal::*;
pub mod crypto;
pub use crypto::*;
pub mod utils;
pub use utils::*;
pub mod render;
pub use render::*;
pub mod routes;
pub use routes::api::*;
pub use routes::sse::*;
pub use routes::pages::*;

static AES256_KEY: std::sync::OnceLock<[u8; 32]> = std::sync::OnceLock::new();

fn load_rustls_config() -> ServerConfig {
  let cert_file = &mut BufReader::new(File::open(IB_CA_CERT).unwrap());
  let key_file  = &mut BufReader::new(File::open(IB_CA_KEY).unwrap());

  let cert_chain: Vec<CertificateDer> = certs(cert_file).map(|c| c.unwrap()).collect();
  let key = private_key(key_file).unwrap().unwrap();

  ServerConfig::builder()
    .with_no_client_auth()
    .with_single_cert(cert_chain, key)
    .unwrap()
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
  rustls::crypto::aws_lc_rs::default_provider()
    .install_default()
    .expect("Failed to install rustls crypto provider");

  let _ = dotenvy::from_path(IB_ENV);
  let _ = dotenvy::from_path(GITHUB_CLIENT_SECRET_ENV);
  let _ = dotenvy::from_path(MYSQL_ENV);
  let _ = dotenvy::from_path(PAYPAL_ENV);
  let _ = dotenvy::from_path(AES256_KEY_ENV);

  let key_str = std::env::var("AES256_KEY").expect("Missing AES256_KEY in environment file or shell");
  let mut key_bytes = [0u8; 32];
  let bytes = key_str.as_bytes();
  if bytes.len() != 32 {
      panic!("AES256_KEY must be exactly 32 bytes long. Provided key was {} bytes.", bytes.len());
  }
  key_bytes.copy_from_slice(bytes);
  AES256_KEY.set(key_bytes).expect("Failed to set AES256_KEY");

  let db_pool = create_db_pool()
    .await
    .expect("Failed to connect to MySQL");

  ensure_database_schema(&db_pool)
    .await
    .expect("Failed to ensure database schema");

  backfill_recent_post_tags(&db_pool)
    .await
    .expect("Failed to backfill post tags");

  let (sse_sender, _) = tokio::sync::broadcast::channel(1000);

  let redis_client = redis::Client::open("redis://127.0.0.1/")
    .expect("Failed to create Redis client");
  let redis_pool = redis::aio::ConnectionManager::new(redis_client)
    .await
    .expect("Failed to connect to Redis");

  let app_state = AppState {
    db_pool,
    github_client_id: std::env::var("GITHUB_CLIENT_ID")
      .expect("Missing GITHUB_CLIENT_ID in environment file or shell"),
    github_client_secret: std::env::var("GITHUB_CLIENT_SECRET")
      .expect("Missing GITHUB_CLIENT_SECRET in environment file or shell"),
    sse_sender,
    redis_pool,
  };

  let http_server = HttpServer::new(|| {
    App::new().default_service(web::to(redirect_to_https))
  })
  .bind(("0.0.0.0", HTTP_PORT))?
  .run();

  let https_server = HttpServer::new(move || {
    let allowed_origin = format!("https://{}", DOMAIN);
    let cors = Cors::default()
      .allowed_origin(&allowed_origin)
      .allowed_methods(vec!["GET", "POST"])
      .allow_any_header();

    App::new()
      .wrap(cors)
      .wrap_fn(move |req, srv| {
        let method = req.method().clone();
        let host = req
          .connection_info()
          .host()
          .split(':')
          .next()
          .unwrap_or_default()
          .to_owned();
        let host_ok = host.trim_end_matches('.').eq_ignore_ascii_case(DOMAIN);

        let origin_ok = req
          .headers()
          .get("origin")
          .and_then(|v| v.to_str().ok())
          .map(|origin| origin.eq_ignore_ascii_case(&allowed_origin))
          .unwrap_or(true);

        let method_ok = method == Method::GET || method == Method::POST || method == Method::HEAD;

        type MiddlewareFuture = std::pin::Pin<
          Box<
            dyn std::future::Future<
              Output = Result<
                actix_web::dev::ServiceResponse<
                  actix_web::body::EitherBody<actix_web::body::BoxBody>
                >,
                actix_web::Error,
              >,
            >,
          >,
        >;

        if !host_ok || (method == Method::POST && !origin_ok) {
          let response = req.into_response(HttpResponse::Forbidden().body("Forbidden"));
          let fut: MiddlewareFuture = Box::pin(async move {
            Ok(response.map_into_right_body::<actix_web::body::BoxBody>())
          });
          return fut;
        }

        if !method_ok {
          let response = req.into_response(HttpResponse::MethodNotAllowed().body("Method Not Allowed"));
          let fut: MiddlewareFuture = Box::pin(async move {
            Ok(response.map_into_right_body::<actix_web::body::BoxBody>())
          });
          return fut;
        }

        let fut = srv.call(req);
        let fut: MiddlewareFuture = Box::pin(async move {
          let res = fut.await?;
          let res = res.map_into_boxed_body();
          Ok(res.map_into_left_body::<actix_web::body::BoxBody>())
        });
        fut
      })
      .app_data(web::Data::new(app_state.clone()))
      .service(hello)
      .service(events_endpoint)
      .service(create_post)
      .service(create_reply)
      .service(show_post)
      .service(show_post_get)
      .service(embed_post_get)
      .service(edit_profile)
      .service(update_profile)
      .service(delete_post)
      .service(edit_post)
      .service(update_post)
      .service(acknowledge_post)
      .service(view_profile)
      .service(get_posts_page)
      .service(get_followers_page)
      .service(user_hover_card_data)
      .service(get_commander_badge)
      .service(follow_user)
      .service(unfollow_user)
      .service(get_war_room_posts_page)
      .service(search_users)
      .service(search_posts)
      .service(search_projects)
      .service(search_section)
      .service(projects_page)
      .service(create_project_profile)
      .service(update_project_profile)
      .service(quick_response_force_project)
      .service(ads_admin_page)
      .service(ads_admin_create)
      .service(ads_admin_update)
      .service(ads_admin_delete)
      .service(ads_user_page)
      .service(ads_user_create)
      .service(ads_user_pay)
      .service(ads_paypal_return)
      .service(ads_paypal_cancel)
      .service(ads_user_update)
      .service(ads_user_delete)
      .service(war_room)
      .service(inbox)
      .service(get_inbox_contacts_page)
      .service(send_direct_message)
      .service(ad_click)
      .service(direct_messages)
      .service(direct_message_unread_count)
      .service(github_auth_start_v1)
      .service(github_auth_callback_v1)
      .service(mobile_shell_html)
      .service(mobile_shell_manifest)
      .service(mobile_shell_service_worker)
      .service(Files::new("/", "./webroot").default_handler(
          actix_web::web::to(|| async {
              actix_web::HttpResponse::NotFound().body("404 Not Found")
          })
      ))
  })
  .bind_rustls_0_23(("0.0.0.0", HTTPS_PORT), load_rustls_config())?
  .run();

  tokio::try_join!(http_server, https_server)?;
  Ok(())
}